Repository python-lsp/python-lsp-server, pull requests merged in 2023-09, with the labels that each got.

#433 Fix null reference for syntax errors due to invalid encodings (Pyflakes)
  pylsp/plugins/pyflakes_lint.py
Labels: bug

#434 Don't set cwd in Popen kwargs when document root is empty (flake8)
  pylsp/plugins/flake8_lint.py
Labels: bug

#432 Use invalid request handler rather than raising key error for requests after shutdown
  pylsp/lsp.py
  pylsp/python_lsp.py
  pyproject.toml
Labels: bug

#435 Update changelog for 1.8.0
  CHANGELOG.md
Labels: task

#436 Add black reformatting commit to `.git-blame-ignore-revs`
  .git-blame-ignore-revs
Labels: task

#440 Fix `include_declaration` handling in references request
  pylsp/plugins/references.py
  test/plugins/test_references.py
Labels: bug

#441 Pass a single copy of the document's source around for flake8
  pylsp/plugins/flake8_lint.py
Labels: bug

#443 Allow Jedi "goto" to perform multiple hops for "go to definition"
  pylsp/plugins/definition.py
  test/plugins/test_definitions.py
Labels: enhancement
