Repository python-lsp/python-lsp-server, pull requests merged in 2023-10, with the labels that each got.

#447 Fix numpy go-to-definition by taking it off autoimport list for this case
  pylsp/plugins/definition.py
  test/plugins/test_definitions.py
Labels: enhancement

#449 Increase minimal required version of autopep8 to `>=2.0.4,<2.1.0`
  pyproject.toml
Labels: bug, task

#450 Fix renaming when file has no EOLs
  pylsp/plugins/jedi_rename.py
  pylsp/plugins/rope_rename.py
  test/plugins/test_jedi_rename.py
  test/plugins/test_rope_rename.py
Labels: bug

#451 Update changelog for 1.8.1
  CHANGELOG.md
Labels: task

#454 Fix notebook document selector not being a list in capabilities
  pylsp/python_lsp.py
  test/test_notebook_document.py
Labels: bug

#456 Update changelog for 1.8.2
  CHANGELOG.md
Labels: task

#457 Fix missing signatures for docstrings in Markdown
  pylsp/_utils.py
  test/test_utils.py
Labels: enhancement

#461 Load `rope_autoimport` cache on `workspace/didChangeConfiguration`
  pylsp/hookspecs.py
  pylsp/plugins/rope_autoimport.py
  pylsp/python_lsp.py
Labels: enhancement

#462 Make workspace/didChangeConfig work with notebook documents
  pylsp/workspace.py
  test/test_notebook_document.py
Labels: enhancement

#464 Minor bug fix in Rope autoimport plugin
  pylsp/plugins/rope_autoimport.py
Labels: bug

#466 Ignore notebook names on cell completion for autoimport
  pylsp/hookspecs.py
  pylsp/plugins/rope_autoimport.py
  pylsp/python_lsp.py
  pylsp/workspace.py
  test/fixtures.py
  test/plugins/test_autoimport.py
  test/test_language_server.py
  test/test_notebook_document.py
  test/test_utils.py
Labels: enhancement

#459 Support `initializationOptions` to configure the server
  pylsp/config/config.py
  test/test_configuration.py
  test/test_utils.py
Labels: enhancement

#469 Pass argument `extendIgnore` to flake8
  CONFIGURATION.md
  pylsp/config/flake8_conf.py
  pylsp/config/schema.json
  pylsp/plugins/flake8_lint.py
Labels: enhancement

#471 Add code completions to `rope_autoimport` plugin
  CONFIGURATION.md
  docs/autoimport.md
  pylsp/config/schema.json
  pylsp/plugins/rope_autoimport.py
  pylsp/python_lsp.py
  pylsp/workspace.py
  test/fixtures.py
  test/plugins/test_autoimport.py
Labels: enhancement
