Repository python-lsp/python-lsp-server, pull requests merged in 2024-07, with the labels that each got.

#570 Fix Fedora instructions
  README.md
Labels: documentation

#586 Update versions of Github actions used on CI
  .github/workflows/static.yml
  .github/workflows/test-linux.yml
  .github/workflows/test-mac.yml
  .github/workflows/test-win.yml
Labels: task

#559 Add `extendSelect` option to flake8 plugin
  CONFIGURATION.md
  pylsp/config/flake8_conf.py
  pylsp/config/schema.json
  pylsp/plugins/flake8_lint.py
Labels: enhancement

#573 Add `window/logMessage` support
  pylsp/python_lsp.py
  pylsp/workspace.py
Labels: enhancement

#584 Use `%r` to have a better log
  pylsp/_utils.py
Labels: enhancement

#581 Set return type to `None` for functions without returns
  pylsp/__main__.py
  pylsp/config/config.py
  pylsp/config/source.py
  pylsp/hookspecs.py
  pylsp/plugins/_resolvers.py
  pylsp/plugins/_rope_task_handle.py
  pylsp/plugins/preload_imports.py
  pylsp/plugins/pycodestyle_lint.py
  pylsp/plugins/pydocstyle_lint.py
  pylsp/plugins/pyflakes_lint.py
  pylsp/plugins/rope_autoimport.py
  pylsp/python_lsp.py
  pylsp/workspace.py
  scripts/jsonschema2md.py
  test/fixtures.py
  test/plugins/test_autoimport.py
  test/plugins/test_autopep8_format.py
  test/plugins/test_completion.py
  test/plugins/test_definitions.py
  test/plugins/test_flake8_lint.py
  test/plugins/test_folding.py
  test/plugins/test_highlight.py
  test/plugins/test_hover.py
  test/plugins/test_jedi_rename.py
  test/plugins/test_mccabe_lint.py
  test/plugins/test_pycodestyle_lint.py
  test/plugins/test_pydocstyle_lint.py
  test/plugins/test_pyflakes_lint.py
  test/plugins/test_pylint_lint.py
  test/plugins/test_references.py
  test/plugins/test_signature.py
  test/plugins/test_symbols.py
  test/plugins/test_yapf_format.py
  test/test_configuration.py
  test/test_document.py
  test/test_language_server.py
  test/test_notebook_document.py
  test/test_text_edit.py
  test/test_uris.py
  test/test_utils.py
  test/test_workspace.py
Labels: enhancement, task
